CREATE TABLE [dbo].[ETL_TYPE]
(
	ETL_TYPE_ID INT NOT NULL,
	ETL_TYPE_NAME VARCHAR(100) NOT NULL,
	ETL_TYPE_SHORT_NAME VARCHAR(10) NOT NULL,
	ETL_TYPE_DESCRIPTION VARCHAR(255) NULL,
	CONSTRAINT [PK_ETL_TYPE] PRIMARY KEY(ETL_TYPE_ID)
)
