CREATE TABLE [dbo].[ETL_PROCESS_LOG]
(
	ETL_PROCESS_LOG_ID BIGINT NOT NULL IDENTITY(1,1),
	ETL_PACKAGE_ID INT NOT NULL,
	MACHINE_NAME VARCHAR(255) NULL,
	EXECUTE_USER VARCHAR(100) NOT NULL,
	START_TIME DATETIME NOT NULL,
	END_TIME DATETIME NULL,
	ETL_STATUS_ID INT NOT NULL,
	CONSTRAINT [PK_ETL_PROCESS_LOG] PRIMARY KEY(ETL_PROCESS_LOG_ID),
	CONSTRAINT [FK_ETL_PROCESS_LOG_ETL_PACKAGE_ID] FOREIGN KEY(ETL_PACKAGE_ID) REFERENCES dbo.ETL_PACKAGE(ETL_PACKAGE_ID),
	CONSTRAINT [FK_ETL_PROCESS_LOG_ETL_STATUS_ID] FOREIGN KEY(ETL_STATUS_ID) REFERENCES dbo.ETL_STATUS(ETL_STATUS_ID)
)
