CREATE TABLE [dbo].[ETL_ERROR_LOG]
(
	ETL_ERROR_LOG_ID BIGINT NOT NULL IDENTITY(1,1),
	ETL_PROCESS_LOG_ID BIGINT NOT NULL,
	ETL_ERROR_MSG VARCHAR(1000),
	ETL_COMPONENT_NAME VARCHAR(500),
	CREATE_TIME DATETIME NOT NULL,
	CONSTRAINT [PK_ETL_ERROR_LOG] PRIMARY KEY(ETL_ERROR_LOG_ID),
	CONSTRAINT [FK_ETL_ERROR_LOG_ETL_PROCESS_LOG_ID] FOREIGN KEY(ETL_PROCESS_LOG_ID) REFERENCES dbo.ETL_PROCESS_LOG(ETL_PROCESS_LOG_ID)
)
