CREATE TABLE [dbo].[ETL_TYPE]
(
	ETL_TYPE_ID INT NOT NULL,
	ETL_TYPE_NAME NVARCHAR(100) NOT NULL,
	ETL_TYPE_SHORT_NAME NVARCHAR(10) NOT NULL,
	ETL_TYPE_DESCRIPTION NVARCHAR(255) NULL,
	CONSTRAINT [PK_ETL_TYPE] PRIMARY KEY(ETL_TYPE_ID)
)
