CREATE TABLE [dbo].[ETL_STATUS]
(
	[ETL_STATUS_ID] INT NOT NULL, 
    [ETL_STATUS_NAME] NVARCHAR(20) NOT NULL, 
    [ETL_STATUS_DESC] NVARCHAR(200) NULL,
	CONSTRAINT [PK_ETL_STATUS] PRIMARY KEY(ETL_STATUS_ID)
)
