CREATE PROCEDURE [dbo].[usp_InsertLogStart]
	@ETL_PACKAGE_ID INT,
	@MACHINE_NAME NVARCHAR(255),
	@EXECUTE_USER NVARCHAR(100),
	@ETL_PROCESS_LOG_ID BIGINT OUTPUT
AS
BEGIN
	INSERT dbo.ETL_PROCESS_LOG(ETL_PACKAGE_ID,MACHINE_NAME,EXECUTE_USER,START_TIME,ETL_STATUS_ID)
	VALUES(@ETL_PACKAGE_ID,@MACHINE_NAME,@EXECUTE_USER,GETDATE(),1);
	SELECT @ETL_PROCESS_LOG_ID = @@IDENTITY;
END
/*
EXEC [dbo].[usp_InsertLogStart]
	@ETL_PACKAGE_ID = ?,
	@MACHINE_NAME = ?,
	@EXECUTE_USER= ?,
	@ETL_PROCESS_LOG_ID = ? OUTPUT
*/
