CREATE PROCEDURE [dbo].[usp_RegisterPackage]
	@ETL_PACKAGE_NAME NVARCHAR(255),
	@ETL_PACKAGE_DESCRIPTION NVARCHAR(800),
	@ETL_TYPE_ID INT,
	@ETL_PACKAGE_ID INT OUTPUT
AS
BEGIN
	MERGE DBO.ETL_PACKAGE AS T
	USING (
		SELECT 
			@ETL_PACKAGE_NAME AS ETL_PACKAGE_NAME,
			@ETL_PACKAGE_DESCRIPTION AS ETL_PACKAGE_DESCRIPTION,
			@ETL_TYPE_ID AS ETL_TYPE_ID
	) AS S
	ON T.ETL_PACKAGE_NAME = S.ETL_PACKAGE_NAME
	AND T.ETL_TYPE_ID = S.ETL_TYPE_ID
	WHEN NOT MATCHED THEN
	INSERT(
		ETL_PACKAGE_NAME,
		ETL_PACKAGE_DESCRIPTION,
		ETL_TYPE_ID,
		Created,
		Modified
	)
	VALUES(
		S.ETL_PACKAGE_NAME,
		S.ETL_PACKAGE_DESCRIPTION,
		S.ETL_TYPE_ID,
		GETDATE(),
		GETDATE()
	)
	WHEN MATCHED AND T.ETL_PACKAGE_DESCRIPTION <> S.ETL_PACKAGE_DESCRIPTION THEN
	UPDATE
	SET T.ETL_PACKAGE_DESCRIPTION = S.ETL_PACKAGE_DESCRIPTION
	;
	SELECT @ETL_PACKAGE_ID = ETL_PACKAGE_ID
	FROM DBO.ETL_PACKAGE
	WHERE ETL_PACKAGE_NAME = @ETL_PACKAGE_NAME AND ETL_TYPE_ID = @ETL_TYPE_ID
END
/*
EXEC [dbo].[usp_RegisterPackage]
	@ETL_PACKAGE_NAME = ?,
	@ETL_PACKAGE_DESCRIPTION = ?,
	@ETL_TYPE_ID = ?,
	@ETL_PACKAGE_ID = ? OUTPUT
*/
