CREATE PROCEDURE [dbo].[usp_UpdateLogEnd]
	@ETL_PROCESS_LOG_ID INT,
	@ETL_STATUS_ID INT
AS
BEGIN
	UPDATE dbo.ETL_PROCESS_LOG
	SET END_TIME = GETDATE(),
	ETL_STATUS_ID = @ETL_STATUS_ID
	WHERE ETL_PROCESS_LOG_ID = @ETL_PROCESS_LOG_ID;
END
