CREATE PROCEDURE [dbo].[usp_UpdateProcessAudit]
	@ETL_PROCESS_AUDIT_ID BIGINT,
	@ETL_STATUS_ID INT,
	@INSERTED_ROWS BIGINT = -1,
	@UPDATED_ROWS BIGINT = -1,
	@DELETED_ROWS BIGINT = -1,
	@INCREMENTAL_FLAG NVARCHAR(100) = NULL
AS
BEGIN
	UPDATE DBO.ETL_PROCESS_AUDIT
	SET
		INSERTED_ROWS = @INSERTED_ROWS,
		UPDATED_ROWS = @UPDATED_ROWS,
		DELETED_ROWS = @DELETED_ROWS,
		ETL_STATUS_ID = @ETL_STATUS_ID,
		INCREMENTAL_FLAG = CASE WHEN @ETL_STATUS_ID = 3 THEN INCREMENTAL_FLAG ELSE @INCREMENTAL_FLAG END,
		END_TIME = GETDATE()
	WHERE ETL_PROCESS_AUDIT_ID = @ETL_PROCESS_AUDIT_ID
END

/*
EXEC [dbo].[usp_UpdateProcessAudit]
	@ETL_PROCESS_AUDIT_ID = ?,
	@ETL_STATUS_ID = ?,
	@INSERTED_ROWS = ?,
	@UPDATED_ROWS = ?,
	@DELETED_ROWS = ?,
	@INCREMENTAL_FLAG = ?
*/
