CREATE PROCEDURE [dbo].[usp_GetIncrementalStart]
	@SOURCE_DB NVARCHAR(100),
	@SOURCE_NAME NVARCHAR(100),
	@TARGET_DB NVARCHAR(100),
	@TARGET_NAME NVARCHAR(100),
	@INCREMENTAL_FLAG NVARCHAR(100) OUTPUT
AS
BEGIN
	SET @INCREMENTAL_FLAG = '2001-01-01 00:00:00'
	SELECT TOP 1 @INCREMENTAL_FLAG = INCREMENTAL_FLAG
	FROM DBO.ETL_PROCESS_AUDIT WITH(NOLOCK)
	WHERE SOURCE_DB = @SOURCE_DB
	AND SOURCE_NAME = @SOURCE_NAME
	AND TARGET_DB = @TARGET_DB
	AND TARGET_NAME = @TARGET_NAME
	AND ETL_STATUS_ID = 2
	ORDER BY START_TIME DESC
END
/*
EXEC [dbo].[usp_GetIncrementalStart]
	@SOURCE_DB = ?,
	@SOURCE_NAME = ?,
	@TARGET_DB = ?,
	@TARGET_NAME = ?,
	@INCREMENTAL_FLAG = ? OUTPUT
*/