CREATE PROCEDURE [dbo].[usp_InsertProcessAudit]
	@ETL_PROCESS_LOG_ID BIGINT,
	@ETL_COMPONENT_NAME NVARCHAR(500),
	@SOURCE_NAME NVARCHAR(100),
	@TARGET_NAME NVARCHAR(100),
	@SOURCE_DB NVARCHAR(100),
	@TARGET_DB NVARCHAR(100),
	@INCREMENTAL_FLAG NVARCHAR(100),
	@ETL_PROCESS_AUDIT_ID BIGINT OUTPUT
AS
BEGIN
	INSERT INTO DBO.ETL_PROCESS_AUDIT(ETL_PROCESS_LOG_ID,ETL_COMPONENT_NAME,SOURCE_NAME,TARGET_NAME,INCREMENTAL_FLAG,START_TIME,ETL_STATUS_ID,SOURCE_DB,TARGET_DB)
	VALUES(@ETL_PROCESS_LOG_ID,@ETL_COMPONENT_NAME,@SOURCE_NAME,@TARGET_NAME,@INCREMENTAL_FLAG,GETDATE(),1,@SOURCE_DB,@TARGET_DB)
	SELECT @ETL_PROCESS_AUDIT_ID = @@IDENTITY
END
/*
EXEC [dbo].[usp_InsertProcessAudit]
	@ETL_PROCESS_LOG_ID = ?,
	@ETL_COMPONENT_NAME = ?,
	@SOURCE_NAME = ?,
	@TARGET_NAME = ?,
	@INCREMENTAL_FLAG = ?,
	@SOURCE_DB = ?,
	@TARGET_DB = ?,
	@ETL_PROCESS_AUDIT_ID = ? OUTPUT
*/