CREATE PROCEDURE [dbo].[usp_InsertProcessAudit]
	@ETL_PROCESS_LOG_ID BIGINT,
	@ETL_COMPONENT_NAME VARCHAR(500),
	@SOURCE_NAME VARCHAR(100),
	@TARGET_NAME VARCHAR(100),
	@INCREMENTAL_FLAG VARCHAR(100),
	@ETL_PROCESS_AUDIT_ID BIGINT OUTPUT
AS
BEGIN
	INSERT INTO DBO.ETL_PROCESS_AUDIT(ETL_PROCESS_LOG_ID,ETL_COMPONENT_NAME,SOURCE_NAME,TARGET_NAME,INCREMENTAL_FLAG,START_TIME,ETL_STATUS_ID)
	VALUES(@ETL_PROCESS_LOG_ID,@ETL_COMPONENT_NAME,@SOURCE_NAME,@TARGET_NAME,@INCREMENTAL_FLAG,GETDATE(),1)
	SELECT @ETL_PROCESS_AUDIT_ID = @@IDENTITY
END
/*
EXEC [dbo].[usp_InsertProcessAudit]
	@ETL_PROCESS_LOG_ID = ?,
	@ETL_COMPONENT_NAME = ?,
	@SOURCE_NAME = ?,
	@TARGET_NAME = ?,
	@INCREMENTAL_FLAG = ?,
	@ETL_PROCESS_AUDIT_ID = ? OUTPUT
*/