CREATE PROCEDURE [dbo].[usp_InsertErrorLog]
	@ETL_PROCESS_LOG_ID INT,
	@ETL_ERROR_MSG VARCHAR(1000),
	@ETL_COMPONENT_NAME VARCHAR(500)
AS
BEGIN
	INSERT dbo.ETL_ERROR_LOG(ETL_PROCESS_LOG_ID,ETL_ERROR_MSG,ETL_COMPONENT_NAME,CREATE_TIME)
	VALUES(@ETL_PROCESS_LOG_ID,@ETL_ERROR_MSG,@ETL_COMPONENT_NAME,GETDATE());
END
